### ISSUE TITLE
SERIALPORT

### ISSUE THREAD

**Issue by S5647787** [ElectronicCats/LoRa_Sniffer#41]
Hello. I encountered an error after changing node(V10.24.1) to install npm and I had to install serial port.

![2](https://github.com/ElectronicCats/LoRa_Sniffer/assets/153599676/692f90f0-edb5-4d70-a3ca-0126d74b0f2b)

After I changed my Python version from 3 to 2, a series of bugs were solved, but I could not install the serial port.

![ERROR](https://github.com/ElectronicCats/LoRa_Sniffer/assets/153599676/e1873281-7727-4a6b-919b-33cb45d03ff9)

Please guide me

**Comment by sabas1080** [comment]
Hi @S5647787 , this project has been discontinued, we have been working on the firmware side with other projects like Catsniffer and CatWAN USB Stick.
